export default {
  OemMake: 0,
  FanAuto: 'disabled',
  FreeAir: 'disabled',
  UnitLocked: 'false',
  AirflowLock: 'onMin',
  SysType: '320',
  NoOfZones: 7,
  NoOfConst: 1,
  EcoMin: '15.0',
  EcoMax: '30.0',
  EcoLock: 'true',
  Id: 0,
  ACError: ' OK',
  Warnings: 'none',
  Tag2: 'System Name 2',
  Tag1: 'System Name',
  CtrlZone: 15,
  RAS: 'RAS',
  Temp: '26.0',
  Setpoint: '25.0',
  Supply: '29.0',
  UnitType: 'Panasonic',
  SleepTimer: 0,
  SysFan: 'med',
  SysMode: 'cool',
  SysOn: 'off',
  DeviceType: 'ASH',
  AirStreamDeviceUId: '000000001',
}
