export const zones1_4Response = [
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 0,
    "Name": "Living",
    "Type": "auto",
    "Mode": "open",
    "SetPoint": 22,
    "Temp": 20.92,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 1,
    "Name": "Front Room",
    "Type": "auto",
    "Mode": "open",
    "SetPoint": 22,
    "Temp": 20.239999,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 2,
    "Name": "Stairs",
    "Type": "const",
    "Mode": "close",
    "SetPoint": 23,
    "Temp": 0,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 0,
    "ConstA": "true",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 3,
    "Name": "Bedroom",
    "Type": "auto",
    "Mode": "close",
    "SetPoint": 21,
    "Temp": 20.239999,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  }
]

export const zones5_8Response = [
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 4,
    "Name": "Office",
    "Type": "auto",
    "Mode": "close",
    "SetPoint": 21,
    "Temp": 20.239999,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 5,
    "Name": "Bedroom 2",
    "Type": "auto",
    "Mode": "close",
    "SetPoint": 21,
    "Temp": 20.5,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 6,
    "Name": "Spare Room",
    "Type": "auto",
    "Mode": "open",
    "SetPoint": 21,
    "Temp": 19.809999,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 7,
    "Name": "Zone 8",
    "Type": "opcl",
    "Mode": "open",
    "SetPoint": 23,
    "Temp": 0,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "true",
    "Master": "false",
    "iSense": "off"
  }
]

export const zones9_12Response = [
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 8,
    "Name": "Zone 9",
    "Type": "opcl",
    "Mode": "open",
    "SetPoint": 23,
    "Temp": 0,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 9,
    "Name": "Zone 10",
    "Type": "opcl",
    "Mode": "open",
    "SetPoint": 23,
    "Temp": 0,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 10,
    "Name": "Zone 11",
    "Type": "opcl",
    "Mode": "open",
    "SetPoint": 23,
    "Temp": 0,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  },
  {
    "AirStreamDeviceUId": "000001234",
    "Id": 0,
    "Index": 11,
    "Name": "Zone 12",
    "Type": "opcl",
    "Mode": "open",
    "SetPoint": 23,
    "Temp": 0,
    "MaxAir": 100,
    "MinAir": 0,
    "Const": 255,
    "ConstA": "false",
    "DmpFlt": "false",
    "Master": "false",
    "iSense": "off"
  }
]

const removeTemps = zones => zones.map( zone => ({...zone, Temp: 0}))

export const zones1_4ResponseNoSensor = removeTemps(zones1_4Response)
export const zones5_8ResponseNoSensor = removeTemps(zones5_8Response)
export const zones9_12ResponseNoSensor = removeTemps(zones9_12Response)
